short_url/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urls.urls')),
]

urls/urls.py
from django.urls import path
from . import views

app_name = 'urls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:key>', views.redirectTo, name='redirectTo'),
    path('shorted/<int:num>', views.shorted, name='shorted'),
]

urls/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
    num = models.AutoField(primary_key=True)
    url = models.URLField(null=False)
    created_datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.url

urls/forms.py
from django.forms import ModelForm, fields
from .models import Url

class MainForm(ModelForm):
    class Meta:
        model = Url
        fields = ('url',)

urls/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import MainForm
from .models import Url
from urls.module.common import ShortURL

def index(request):
    if request.method == "POST":
        form = MainForm(request.POST)
        if form.is_valid():
            url = form.save()
            return redirect('urls:shorted', url.num)
    else:
        form = MainForm
        return render(request, 'urls/index.html', {'form':form })

def shorted(request, num):
    shortURL = ShortURL() 
    code = shortURL.encode(num = num)
    context = {'code': code}
    return render(request, 'urls/shorted.html', context)

def redirectTo(request, key):
    shortURL = ShortURL() 
    decodedNum = shortURL.decode(key = key)
    url = get_object_or_404(Url, num= decodedNum)
    return redirect(url.url)

urls/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">
</head>
<body>
    <div style="background-color: #f5f5f5;">
        <div class="container" >
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

urls/templates/urls/index.html
{% extends "base.html" %}

{% block body %}
<div class="d-flex align-items-center justify-content-center" style='height: 100vh;'>
    <div class="text-center">
        <h1>URL短縮サービス</h1>

        <form action="{% url 'urls:index' %}" method="POST">
            {% csrf_token %}
            <div class='mb-2'>
            <!-- ：{{ form.url }} -->
            <input style="width:100%;" type="url" name="url" id="id_url" maxlength="200" required placeholder="短縮したいURL">
            </div>
            <input class="btn btn-success" type="submit" value="短縮化">
        </form> 
    </div>

</div>
{% endblock %}

urls/templates/urls/shorted.html
{% extends "base.html" %}

{% block body %}
<div class="d-flex align-items-center justify-content-center" style='height: 100vh;'>
    <div class="text-center">
        <h1>URL短縮サービス</h1>
        <h3>短縮後: <a href="/{{ code }}">http://127.0.0.1:8000/{{ code }}</a></p>
        
        <a href="../" class="btn btn-primary">別のURLを短縮する</a>
    
        <p class="mt-5" >
            <a href="https://github.com/azain4645/shortUrl">ソースコードはこちらから</a>
        </p>
    </div>

</div>

{% endblock %}